# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/admin2/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/admin2/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/admin2/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/admin2/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/admin2/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/admin2/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/admin2/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/admin2/anaconda3/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,S

#### 3. Create a null vector of size 10

In [3]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [4]:
print(x.size*x.itemsize) 
#memory size of numpy array in bytes

80


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [5]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [6]:
x = np.zeros(10)
x[5]=1
print(x)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [7]:
vec = np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [8]:
print(np.flip(vec))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
x = np.arange(0,9)
print(x.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [49]:
s = ([1,2,0,0,4,0])
print(np.nonzero(s))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix

In [11]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [12]:
x = np.random.random((3,3,3))
print(x)

[[[0.56131086 0.06952337 0.91786105]
  [0.85149465 0.45306591 0.43006112]
  [0.1163313  0.03411322 0.99397748]]

 [[0.96900317 0.87717645 0.07042846]
  [0.27862751 0.65405696 0.61782128]
  [0.74658694 0.30797301 0.90545743]]

 [[0.78833718 0.21750606 0.72847706]
  [0.70836102 0.12020644 0.84834718]
  [0.4777296  0.03576662 0.6771404 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [50]:
x = np.random.random((10,10))
print(x.min(),x.max())

0.00896889186439731 0.9973532749919126


#### 14. Create a random vector of size 30 and find the mean value

In [53]:
x = np.random.random(30)
print(x)
sum = 0
for i in x:
    sum += i
val = sum/30
print(val)
print(np.mean(x))


[0.46261494 0.94138966 0.93768373 0.73671747 0.50449742 0.94499857
 0.54355456 0.75388199 0.25759184 0.05307317 0.49753801 0.66768178
 0.4159703  0.60911888 0.04476946 0.21197026 0.33631284 0.97035009
 0.27481911 0.35729942 0.88992834 0.79863075 0.2116383  0.11562773
 0.40172653 0.54541606 0.59353811 0.76338469 0.9046353  0.17325706]
0.5306538771084622
0.5306538771084622


#### 15. Create a 2d array with 1 on the border and 0 inside

In [31]:
x = np.ones((5,5))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [58]:
x = np.ones((5,5))
x = np.pad(x,pad_width=1,mode = 'constant',constant_values = 0)
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [33]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [62]:
x = np.ones((5,5))
s = np.diag(1+np.arange(4),k=-1)
print(s)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [67]:
x = np.zeros((8,8))
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [73]:
np.random.random((6,7,8))
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)
